// product localstorage value key
export const productFormStepValueKeys = {
  stepOne: "Product_Step_One_Value",
  stepTwo: "Product_Step_Two_Value",
  stepThree: "Product_Step_Three_Value",
  stepFour: "Product_Step_Four_Value",
  stepFive: "Product_Step_Five_Value",
};

// product form input field values
export const productBodyStyle = [
  { value: "all", label: "All" },
  { value: "coupe", label: "Coupe" },
  { value: "convertible", label: "Convertible" },
  { value: "hatchback", label: "Hatchback" },
  { value: "sedan", label: "Sedan" },
  { value: "suv/crossover", label: "SUV/Crossover" },
  { value: "truck", label: "Truck" },
  { value: "van/minivan", label: "Van/Minivan" },
  { value: "wagon", label: "Wagon" },
];

export const productTitleStatus = [
  { value: "clean (CT)", label: "Clean (CT)" },
  { value: "salvage", label: "Salvage" },
  { value: "rebuilt/reconstructed", label: "Rebuilt/Reconstructed" },
  { value: "junk", label: "Junk" },
  { value: "buyback", label: "Buyback" },
  { value: "bonded", label: "Bonded" },
  { value: "export only", label: "Export Only" },
  { value: "odometer rollback", label: "Odometer Rollback" },
  { value: "flood", label: "Flood" },
  { value: "non-repairable", label: "Non-Repairable" },
];

export const filterProductTransmission = [
  { value: "all", label: "All" },
  { value: "automatic", label: "Autometic" },
  { value: "manual", label: "Manual" },
];
export const productTransmission = [
  { value: "automatic", label: "Autometic" },
  { value: "manual", label: "Manual" },
];

export const productDrivetrain = [
  { value: "all", label: "All" },
  { value: "fwd", label: "Front-Wheel Drive (FWD)" },
  { value: "rwd", label: "Rear-Wheel Drive (RWD)" },
  { value: "awd", label: "All-Wheel Drive (AWD)" },
  { value: "4wd", label: "Four-Wheel Drive (4WD)" },
];

export const productEngineTypes = [
  { value: "i4", label: "Inline 4 (I4)" },
  { value: "i6", label: "Inline 6 (I6)" },
  { value: "v6", label: "V6" },
  { value: "v8", label: "V8" },
  { value: "v10", label: "V10" },
  { value: "v12", label: "V12" },
  { value: "electric", label: "Electric" },
  { value: "hybrid", label: "Hybrid" },
  { value: "diesel", label: "Diesel" },
  { value: "rotary", label: "Rotary" },
];

export const productMileageOptions = [
  { value: "0-5000", label: "0 - 5,000 miles" },
  { value: "5001-10000", label: "5,001 - 10,000 miles" },
  { value: "10001-20000", label: "10,001 - 20,000 miles" },
  { value: "20001-50000", label: "20,001 - 50,000 miles" },
  { value: "50001-100000", label: "50,001 - 100,000 miles" },
  { value: "100001-150000", label: "100,001 - 150,000 miles" },
  { value: "150001-200000", label: "150,001 - 200,000 miles" },
  { value: "200001+", label: "200,001+ miles" },
];

export const productExteriorColorOptions = [
  { value: "black", label: "Black" },
  { value: "white", label: "White" },
  { value: "gray", label: "Gray" },
  { value: "silver", label: "Silver" },
  { value: "blue", label: "Blue" },
  { value: "darkBlue", label: "Dark Blue" },
  { value: "lightBlue", label: "Light Blue" },
  { value: "red", label: "Red" },
  { value: "darkRed", label: "Dark Red" },
  { value: "green", label: "Green" },
  { value: "darkGreen", label: "Dark Green" },
  { value: "lightGreen", label: "Light Green" },
  { value: "yellow", label: "Yellow" },
  { value: "mustard", label: "Mustard" },
  { value: "orange", label: "Orange" },
  { value: "burntOrange", label: "Burnt Orange" },
  { value: "brown", label: "Brown" },
  { value: "darkBrown", label: "Dark Brown" },
  { value: "gold", label: "Gold" },
  { value: "beige", label: "Beige" },
  { value: "cream", label: "Cream" },
  { value: "purple", label: "Purple" },
  { value: "violet", label: "Violet" },
  { value: "pink", label: "Pink" },
  { value: "hotPink", label: "Hot Pink" },
  { value: "maroon", label: "Maroon" },
  { value: "teal", label: "Teal" },
  { value: "aqua", label: "Aqua" },
  { value: "navy", label: "Navy" },
  { value: "turquoise", label: "Turquoise" },
  { value: "cyan", label: "Cyan" },
  { value: "magenta", label: "Magenta" },
  { value: "lime", label: "Lime" },
  { value: "charcoal", label: "Charcoal" },
  { value: "champagne", label: "Champagne" },
  { value: "bronze", label: "Bronze" },
  { value: "copper", label: "Copper" },
  { value: "burgundy", label: "Burgundy" },
  { value: "ivory", label: "Ivory" },
  { value: "mint", label: "Mint" },
  { value: "peach", label: "Peach" },
  { value: "lavender", label: "Lavender" },
  { value: "plum", label: "Plum" },
  { value: "sand", label: "Sand" },
  { value: "forestGreen", label: "Forest Green" },
  { value: "skyBlue", label: "Sky Blue" },
  { value: "rust", label: "Rust" },
  { value: "olive", label: "Olive" },
  { value: "midnightBlue", label: "Midnight Blue" },
  { value: "sapphire", label: "Sapphire" },
  { value: "emerald", label: "Emerald" },
  { value: "roseGold", label: "Rose Gold" },
  { value: "sunsetOrange", label: "Sunset Orange" },
  { value: "amethyst", label: "Amethyst" },
];

export const productInteriorColorOptions = [
  { value: "black", label: "Black" },
  { value: "beige", label: "Beige" },
  { value: "gray", label: "Gray" },
  { value: "brown", label: "Brown" },
  { value: "tan", label: "Tan" },
  { value: "white", label: "White" },
  { value: "red", label: "Red" },
  { value: "burgundy", label: "Burgundy" },
  { value: "blue", label: "Blue" },
  { value: "navy", label: "Navy" },
  { value: "green", label: "Green" },
  { value: "darkGreen", label: "Dark Green" },
  { value: "yellow", label: "Yellow" },
  { value: "orange", label: "Orange" },
  { value: "cream", label: "Cream" },
  { value: "charcoal", label: "Charcoal" },
  { value: "platinum", label: "Platinum" },
  { value: "ivory", label: "Ivory" },
  { value: "silver", label: "Silver" },
  { value: "taupe", label: "Taupe" },
  { value: "lightGray", label: "Light Gray" },
  { value: "darkGray", label: "Dark Gray" },
  { value: "mint", label: "Mint" },
  { value: "peach", label: "Peach" },
  { value: "lavender", label: "Lavender" },
  { value: "darkBrown", label: "Dark Brown" },
  { value: "chocolate", label: "Chocolate" },
  { value: "khaki", label: "Khaki" },
  { value: "cocoa", label: "Cocoa" },
  { value: "cinnamon", label: "Cinnamon" },
  { value: "steel", label: "Steel" },
  { value: "carmine", label: "Carmine" },
  { value: "ruby", label: "Ruby" },
  { value: "sapphire", label: "Sapphire" },
  { value: "amethyst", label: "Amethyst" },
  { value: "tanLeather", label: "Tan Leather" },
  { value: "blackLeather", label: "Black Leather" },
  { value: "beigeLeather", label: "Beige Leather" },
  { value: "redLeather", label: "Red Leather" },
  { value: "grayLeather", label: "Gray Leather" },
  { value: "brownLeather", label: "Brown Leather" },
];
